# habilita o sink do Prometheus
*.sink.prometheus.class=org.apache.spark.metrics.sink.PrometheusServlet
*.sink.prometheus.path=/metrics/prometheus
*.sink.prometheus.sample-rate=10

# habilita métricas por fonte
driver.source.jvm.class=org.apache.spark.metrics.source.JvmSource
executor.source.jvm.class=org.apache.spark.metrics.source.JvmSource

# habilita métricas do Spark Streaming
#*.source.streaming.class=org.apache.spark.metrics.source.StreamingSource
