# Permite conexões de qualquer interface de rede (dentro da rede do Docker andromeda_network)
bind 0.0.0.0

# Desativa o modo protegido para permitir a comunicação com a Node API e o Spark
protected-mode no

# Define um limite máximo de memória RAM (ajuste conforme a capacidade da sua VM)
maxmemory 512mb

# Estratégia de Evicção: Quando atingir o limite, remove a chave menos utilizada (LRU)
maxmemory-policy allkeys-lru

# Método de persistência (RDB)
# - Salva o estado em disco de forma leve para o caso de reinicializações do container
# - AOF não é necessário, tendo em vista que a visualização no mapa de intensidade não é crítica
save 900 1
save 300 10

# Nome do arquivo de banco de dados e diretório onde será salvo o estado do sistema
dbfilename dump.rdb
dir /data